version: '3.7'

services:
  oracle:
    image: oracle/database:18.4.0-xe
    ports:
      - "1521:1521"   # Untuk koneksi SQL (default Oracle listener)
      - "8888:8080"   # Untuk Oracle APEX / EM Express (port 8080 di container)
    environment:
      - ORACLE_PWD=passwordnyaOracle18c
    shm_size: 1g
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network

volumes:
  oracle-data:

networks:
  oracle-network:
